### ISSUE TITLE
how to use 

### ISSUE THREAD

**Issue by ruchitdonga** [h0nde/roblox-group-scanner#3]
can any one help how to use this

**Comment by glixzzy** [comment]
https://burgs.io/

**Comment by Geographs** [comment]
The website "burgs.io" is said to be a scam. I would recommend staying away from it.

**Comment by ruchitdonga** [comment]
> https://burgs.io/

no one answering in the server

**Comment by Richodev** [comment]
> can any one help how to use this

leave this site.
