### ISSUE TITLE
Webhook won't send

### ISSUE THREAD

**Issue by Alektherblxdev** [h0nde/roblox-group-scanner#5]
When I started the group finder, and it found one, it never sent the webhook. I did -u then my webhook. Am I maybe missing a package? If so which one do you think it is?  Thanks :)

**Comment by h0nde** [comment]
This sounds like an issue on your end, ake sure that the webhook link you entered is correct.

**Comment by Alektherblxdev** [comment]
Figured out why it wasn't working, I used --threads then -u which resulted in it not working. Thanks tho :)
